### ISSUE TITLE
Feature Request: Temporal interpolation

### ISSUE THREAD

**Issue by owang** [kwea123/nsff_pl#1]
I find that being able to view the (spatio)-temporal interpolation (e.g., w/ the spiral path) is a good way to visualize whether the scene flow has been correctly reconstructed or not. The original paper repo supports the forward (splatting) approach to rendering temporal interpolation for reference.

**Comment by kwea123** [comment]
Hi, this is on my to-do list, I am still debugging.

**Comment by owang** [comment]
great to hear!

**Comment by kwea123** [comment]
Done. Please use `--split test_fixviewX_interpY` in eval mode. I have also added several results in README. I will add the bullet-time effect (change view + time interpolation) in the future.
