### ISSUE TITLE
potential tiny mistake in rendering.py 

### ISSUE THREAD

**Issue by alfredoLimo** [kwea123/nsff_pl#16]
rendering.py 
line 231 and 232
            results['xyzs_fw_bw'] = xyz_fw + transient_flows_fw_bw
            results['xyzs_bw_fw'] = xyz_bw + transient_flows_fw_bw
second line may be xyz_bw + transient_flows_bw_fw
should it a tiny but crucial mistake?

**Comment by kwea123** [comment]
Indeed it's a bug. Just fixed it. It's only for regularization loss so I expect the influence would not be that large. Thank you!
