### ISSUE TITLE
download videos 'kid-bubble', 'kid-jumping' and etc

### ISSUE THREAD

**Issue by ziruiw-dev** [kwea123/nsff_pl#8]
Hi @kwea123,

Thanks for this great implementation of NSFF. May I ask do you have links to download videos (apart from the NVIDIA Dynamic Scenes dataset) presented in the NSFF paper? E.g. these ones (fig 7 in the [original paper](https://arxiv.org/abs/2011.13084)):

![Screenshot from 2021-09-06 17-42-28](https://user-images.githubusercontent.com/9391023/132196725-320e0996-7daa-48b6-9a50-a8a0a8bd41bb.png)

I see you have tried the kid with bubble video in your implementation but I cannot find it from the original paper and the official repo.

Best,
Zirui

**Comment by kwea123** [comment]
Hi, sorry for the late reply. The videos other from the `kid-running` have copyright issue, so I cannot share with you (I got the video directly from the paper members)
